### ISSUE TITLE
Could you support the ibus-libzhuyin?

### ISSUE THREAD

**Issue by laichiaheng** [chewing/chewing-editor#238]
# What is your environment?

*   OS version
Arch Linux
Gnome40 Wayland.

ibus-chewing is useless in Wayland, only the ibus-libzhuyin survives, but no editor supports it.

**Comment by jserv** [comment]
Since Fedora 41, the default input method for Traditional Chinese (Taiwan), the zh_TW locale is changed from ibus-libzhuyin to ibus-chewing. ibus-chewing is the ibus front-end of the libchewing library.
See https://fedoraproject.org/wiki/Releases/41/ChangeSet#IBus_Chewing_for_Traditional_Chinese_(Taiwan)_Desktop_by_Default
